### ISSUE TITLE
测试deepsort.engine时报错“[TRT] INVALID_CONFIG: Deserialize the cuda engine failed”

### ISSUE THREAD

**Issue by Mrgao9** [RichardoMrMu/deepsort-tensorrt#2]
尊敬的作者您好，我在win10下做 yolov5+deepsort+tensorRTx 加速时，参考您的这篇文章来操作。
https://blog.csdn.net/weixin_42264234/article/details/120152117
按照教程生成deepsort.onnx、deepsort.engine
![QQ截图20211113111649](https://user-images.githubusercontent.com/22071198/141603989-ec4f1540-8126-43b2-86cb-f066889063de.jpg)
，在运行 demo 项目时，报出如下错误：
![QQ截图20211113111843](https://user-images.githubusercontent.com/22071198/141604011-4d56f37b-92c9-4f5b-953e-bae78c518453.jpg)
经过多次尝试、查询资料，都没能解决。所以期望您能百忙之中给出一些指点！非常感谢！

**Comment by RichardoMrMu** [comment]
你可以尝试用项目里的`CMakeLists_deepsort-tensorrt_win10.txt`代替原来的CMakeLists.txt,看看会不会有问题。

**Comment by Mrgao9** [comment]
> 你可以尝试用项目里的`CMakeLists_deepsort-tensorrt_win10.txt`代替原来的CMakeLists.txt,看看会不会有问题。

@RichardoMrMu 您好，非常感谢您的回复。我就是使用 CMakeLists_deepsort-tensorrt_win10.txt代替原来的CMakeLists.txt做的，依然出现这个问题。
![image](https://user-images.githubusercontent.com/22071198/141708964-16c6b73d-f3b0-49dd-96c2-dced44e34f95.png)

从生成engine文件的日志输出看，开始我怀疑是 tensorRT 与 cuda、cudnn的版本不匹配问题导致，所以我更换了对应的tensorRT版本，也就是解决了图中的警告2。但是还是报同样的错。
会不会和图中警告1有关呢？

**Comment by RichardoMrMu** [comment]
不好意思，因为我的开发环境是jetson nano，linux，所以在windows上的问题，我不太好判断。我已经上传了我生成的[engine file](https://github.com/RichardoMrMu/deepsort-tensorrt/releases/tag/sort)，你可以尝试进行测试，你也可以尝试询问[这位](https://github.com/lbq779660843)，我还是怀疑环境问题，即tensorrt和cuda，cudnn版本。

**Comment by Mrgao9** [comment]
> 不好意思，因为我的开发环境是jetson nano，linux，所以在windows上的问题，我不太好判断。我已经上传了我生成的[engine file](https://github.com/RichardoMrMu/deepsort-tensorrt/releases/tag/sort)，你可以尝试进行测试，你也可以尝试询问[这位](https://github.com/lbq779660843)，我还是怀疑环境问题，即tensorrt和cuda，cudnn版本。

非常感谢，祝您工作顺利，生活愉快！
